name       : goverlay
version    : '0.5'
release    : 7
source     :
    - https://github.com/benjamimgois/goverlay/archive/refs/tags/0.5.tar.gz : e059ecb1d113ddc062f69f8a25225a6acec4294ffa5c8eb725c0bd6a12dce075
license    : GPL-3.0-only
component  : system.utils
summary    : GUI for configuring Vulkan/OpenGL overlays - MangoHud and vkBasalt
description: |
    GOverlay is an open source project aimed to create a Graphical UI to manage Vulkan/OpenGL overlays. It currently supports MangoHud and GOverlay.
builddeps  :
    - pkgconfig(x11)
    - lazarus
    - qt5pas-devel
rundeps    :
    - vulkan-tools
    - mesa-demos
    - vkbasalt
    - mangohud
    - git
build      : |
    lazbuild --lazarusdir=/usr/share/lazarus --bm=Release goverlay.lpi
install    : |
    %make_install prefix=/usr
