name       : goverlay
version    : 0.7.1
release    : 11
source     :
    - https://github.com/benjamimgois/goverlay/archive/refs/tags/0.7.1.tar.gz : 78066ee8933f78f40e261cc3b27fa3021098e60526a85aa2aa821d52a95b7a21
license    : GPL-3.0-only
component  : system.utils
summary    : GUI for configuring Vulkan/OpenGL overlays - MangoHud, vkBasalt and ReplaySorcery
description: |
    GOverlay is an open source project aimed to create a Graphical UI to manage Vulkan/OpenGL overlays. It currently supports MangoHud and GOverlay.
    It also serves as an alternative to Nvidia Shadowplay, alowing you to record gameplay as well as save replays instantly with ReplaySorcery.
builddeps  :
    - pkgconfig(x11)
    - lazarus
    - qt5pas-devel
rundeps    :
    - git
    - mangohud
    - mesa-demos
    - replaysorcery
    - vkbasalt
    - vulkan-tools
build      : |
    lazbuild --lazarusdir=/usr/share/lazarus --bm=Release goverlay.lpi
install    : |
    %make_install prefix=/usr
