name       : goverlay
version    : 0.3.8F
release    : 5
source     :
    - git|https://github.com/benjamimgois/goverlay : e51a04438c83a0ff4248e6c140c0c5a5ec2d416e
license    : GPL-3.0-only
component  : system.utils
summary    : GUI for configuring Vulkan/OpenGL overlays - MangoHud and vkBasalt
description: |
    GOverlay is an open source project aimed to create a Graphical UI to manage Vulkan/OpenGL overlays. It currently supports MangoHud and GOverlay.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - lazarus
rundeps    :
    - vulkan-tools
    - mesa-demos
    - vkbasalt
    - mangohud
    - git
build      : |
    lazbuild --lazarusdir=/usr/share/lazarus --bm=Release goverlay.lpi
install    : |
    %make_install prefix=/usr
