name       : goverlay
version    : 0.4.0
release    : 6
source     :
    - https://github.com/benjamimgois/goverlay/archive/0.4.tar.gz : 435399b13aa8a37b22fa3fd59d32caaaceaf0fdc707d27df14d82904fc1e8bcd
license    : GPL-3.0-only
component  : system.utils
summary    : GUI for configuring Vulkan/OpenGL overlays - MangoHud and vkBasalt
description: |
    GOverlay is an open source project aimed to create a Graphical UI to manage Vulkan/OpenGL overlays. It currently supports MangoHud and GOverlay.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - lazarus
rundeps    :
    - vulkan-tools
    - mesa-demos
    - vkbasalt
    - mangohud
    - git
build      : |
    lazbuild --lazarusdir=/usr/share/lazarus --bm=Release goverlay.lpi
install    : |
    %make_install prefix=/usr
