name       : goverlay
version    : 0.3.8
release    : 4
source     :
    - https://github.com/benjamimgois/goverlay/archive/0.3.8.tar.gz : 253c97dec921a01f6dc41e43de6ffaaf449e1d797cb6278362502eab534fa7b9
license    : GPL-3.0-only
component  : system.utils
summary    : GUI for configuring Vulkan/OpenGL overlays - MangoHud and vkBasalt
description: |
    GOverlay is an open source project aimed to create a Graphical UI to manage Vulkan/OpenGL overlays. It currently supports MangoHud and GOverlay.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - lazarus
rundeps    :
    - vulkan-tools
    - mesa-demos
    - vkbasalt
    - mangohud
    - git
build      : |
    lazbuild --lazarusdir=/usr/share/lazarus goverlay.lpi
install    : |
    %make_install prefix=/usr
