name       : goverlay
version    : 0.6.0
release    : 9
source     :
    - https://github.com/benjamimgois/goverlay/archive/refs/tags/0.6.tar.gz : 056151d79004953bd8e098f28d2338c492c969b0c6b9ff3e64021d41e516755c
license    : GPL-3.0-only
component  : system.utils
summary    : GUI for configuring Vulkan/OpenGL overlays - MangoHud, vkBasalt and ReplaySorcery
description: |
    GOverlay is an open source project aimed to create a Graphical UI to manage Vulkan/OpenGL overlays. It currently supports MangoHud and GOverlay.
    It also serves as an alternative to Nvidia Shadowplay, alowing you to record gameplay as well as save replays instantly with ReplaySorcery.
builddeps  :
    - pkgconfig(x11)
    - lazarus
    - qt5pas-devel
rundeps    :
    - git
    - mangohud
    - mesa-demos
    - replaysorcery
    - vkbasalt
    - vulkan-tools
build      : |
    lazbuild --lazarusdir=/usr/share/lazarus --bm=Release goverlay.lpi
install    : |
    %make_install prefix=/usr
