name       : goverlay
version    : 0.9.1
release    : 14
source     :
    - https://github.com/benjamimgois/goverlay/archive/refs/tags/0.9.1.tar.gz : 1210098a37157c7e11f44f1d450849c2204019266e7bfa4c74f6433d4010fcd3
license    : GPL-3.0-only
component  : system.utils
summary    : GUI for configuring Vulkan/OpenGL overlays - MangoHud, vkBasalt and ReplaySorcery
description: |
    GOverlay is an open source project aimed to create a Graphical UI to manage Vulkan/OpenGL overlays. It currently supports MangoHud and GOverlay.
    It also serves as an alternative to Nvidia Shadowplay, alowing you to record gameplay as well as save replays instantly with ReplaySorcery.
builddeps  :
    - pkgconfig(x11)
    - lazarus
    - qt5pas-devel
rundeps    :
    - git
    - mangohud
    - mesa-demos
    - replaysorcery
    - vkbasalt
    - vulkan-tools
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-mangohud-path-on-Solus.patch
build      : |
    lazbuild --lazarusdir=/usr/share/lazarus --bm=Release goverlay.lpi
install    : |
    %make_install prefix=/usr
