name       : goverlay
version    : 0.3.5
release    : 1
source     :
    - https://github.com/benjamimgois/goverlay/archive/0.3.5.tar.gz : f66d59713bf87234c8a18837499bbbea9225f16cbe8adc6d430ce9b728c47db7
license    : GPL-3.0-only
component  : system.utils
summary    : GUI for configuring Vulkan/OpenGL overlays - MangoHud and vkBasalt
description: |
    GOverlay is an open source project aimed to create a Graphical UI to manage Vulkan/OpenGL overlays. It currently supports MangoHud and GOverlay.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - lazarus
rundeps    :
    - vulkan-tools
    - mesa-demos
    - vkbasalt
    - mangohud
build      : |
    lazbuild --lazarusdir=/usr/share/lazarus goverlay.lpi
install    : |
    %make_install prefix=/usr
