name       : goverlay
version    : 0.5.1
release    : 8
source     :
    - https://github.com/benjamimgois/goverlay/archive/refs/tags/0.5.1.tar.gz : 5811bf6068ad6077fc7a121b2763e111017d0b80ac2538fa05b221b10a3181f6
license    : GPL-3.0-only
component  : system.utils
summary    : GUI for configuring Vulkan/OpenGL overlays - MangoHud and vkBasalt
description: |
    GOverlay is an open source project aimed to create a Graphical UI to manage Vulkan/OpenGL overlays. It currently supports MangoHud and GOverlay.
builddeps  :
    - pkgconfig(x11)
    - lazarus
    - qt5pas-devel
rundeps    :
    - vulkan-tools
    - mesa-demos
    - vkbasalt
    - mangohud
    - git
build      : |
    lazbuild --lazarusdir=/usr/share/lazarus --bm=Release goverlay.lpi
install    : |
    %make_install prefix=/usr
