name       : goverlay
version    : 0.8.1
release    : 12
source     :
    - https://github.com/benjamimgois/goverlay/archive/refs/tags/0.8.1.tar.gz : 5666e926af67d43bdc5d414e9a0249f10cdd5d7fe7d632186cb698cc9abd989e
license    : GPL-3.0-only
component  : system.utils
summary    : GUI for configuring Vulkan/OpenGL overlays - MangoHud, vkBasalt and ReplaySorcery
description: |
    GOverlay is an open source project aimed to create a Graphical UI to manage Vulkan/OpenGL overlays. It currently supports MangoHud and GOverlay.
    It also serves as an alternative to Nvidia Shadowplay, alowing you to record gameplay as well as save replays instantly with ReplaySorcery.
builddeps  :
    - pkgconfig(x11)
    - lazarus
    - qt5pas-devel
rundeps    :
    - git
    - mangohud
    - mesa-demos
    - replaysorcery
    - vkbasalt
    - vulkan-tools
build      : |
    lazbuild --lazarusdir=/usr/share/lazarus --bm=Release goverlay.lpi
install    : |
    %make_install prefix=/usr
